# Generated by Django 5.2.8 on 2025-11-12 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alojamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_alojamiento', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calificacion', models.DecimalField(decimal_places=1, max_digits=3)),
                ('paginaweb', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=50)),
                ('direccion', models.TextField()),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empleado', models.CharField(max_length=255)),
                ('apellido_empleado', models.CharField(max_length=255)),
                ('puesto', models.CharField(max_length=100)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('telefono', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_transporte', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('horario', models.TimeField()),
                ('empresa', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientesViajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_viaje', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_salida', models.DateField()),
                ('fecha_regreso', models.DateField()),
                ('destino', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('alojamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_clientes.alojamiento')),
                ('clientes', models.ManyToManyField(through='app_clientes.ClientesViajes', to='app_clientes.cliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_clientes.empleado')),
                ('transporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_clientes.transporte')),
            ],
        ),
        migrations.AddField(
            model_name='clientesviajes',
            name='viaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_clientes.viaje'),
        ),
        migrations.AlterUniqueTogether(
            name='clientesviajes',
            unique_together={('cliente', 'viaje')},
        ),
    ]
